# Generated by Django 3.2.4 on 2021-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=10)),
                ('task_name', models.CharField(max_length=50)),
                ('task_desc', models.CharField(max_length=700)),
                ('assigned_to', models.CharField(max_length=50)),
                ('submit_time', models.TimeField()),
                ('submit_date', models.DateField()),
            ],
        ),
    ]
