# Generated by Django 3.2.4 on 2021-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_tasks',
            name='task_desc',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
