# Generated by Django 3.2.4 on 2021-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_assigned_tasks_task_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_tasks',
            name='submit_date',
            field=models.DateField(null=True),
        ),
    ]
