# Generated by Django 3.2.4 on 2021-09-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
