# Generated by Django 3.2.4 on 2021-09-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_mytask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='completed',
        ),
    ]
