# Generated by Django 3.2.4 on 2021-10-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_item_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mytask',
        ),
    ]
